package medvedev.com.enums;

public enum SystemConfiguration {

    MIN_AMOUNT_EXCHANGE,
    MAX_AMOUNT_EXCHANGE,
    SYSTEM_STATE,
    MIN_DIFFERENCE_PRICE,
    MIN_DIFFERENCE_PRICE_FIAT_CRYPT,
    CURRENT_PRICE_LEVEL,
    INVIOLABLE_RESIDUE,
    AVAILABLE_MINUTES_COUNT_WITHOUT_EXCHANGE;
}
